// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFak9pLcEaV8UrtaKjDLpGXtuqKc3BFI8',
    appId: '1:1006633812714:web:0e8609c92e9ad9c5014d93',
    messagingSenderId: '1006633812714',
    projectId: 'movies-5c45f',
    authDomain: 'movies-5c45f.firebaseapp.com',
    storageBucket: 'movies-5c45f.firebasestorage.app',
    measurementId: 'G-52RMMSMWZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4_LwR1Nal3NgqBrBekry0JgtnlGXToY0',
    appId: '1:1006633812714:android:0dcccca6c059baad014d93',
    messagingSenderId: '1006633812714',
    projectId: 'movies-5c45f',
    storageBucket: 'movies-5c45f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVewIX-rX9f9kpc4QTAKupS1BSXXdVVI',
    appId: '1:1006633812714:ios:a38520a522b12473014d93',
    messagingSenderId: '1006633812714',
    projectId: 'movies-5c45f',
    storageBucket: 'movies-5c45f.firebasestorage.app',
    iosBundleId: 'com.example.wasawatBoonporn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFak9pLcEaV8UrtaKjDLpGXtuqKc3BFI8',
    appId: '1:1006633812714:web:4e97b5dd9fe26b97014d93',
    messagingSenderId: '1006633812714',
    projectId: 'movies-5c45f',
    authDomain: 'movies-5c45f.firebaseapp.com',
    storageBucket: 'movies-5c45f.firebasestorage.app',
    measurementId: 'G-GNWHS4YVCZ',
  );
}
